name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: prepare java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: 'x64'
      - name: install clojure
        uses: DelaGuardo/setup-clojure@10.0
        with:
          cli: 1.11.1.1347
      - name: clj tests
        run: make test
